//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CallQuality.Core.Resources;

using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Templates {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Templates() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp =
                    new global::System.Resources.ResourceManager(
                        "CallQuality.Core.Resources.Templates",
                        typeof(Templates).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &lt;html lang=&quot;en-US&quot;&gt;
    ///&lt;head&gt;
    /// &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
    /// &lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1.0&quot; /&gt;
    /// &lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
    /// &lt;title&gt;Mailer&lt;/title&gt;
    /// &lt;style type=&quot;text/css&quot;&gt;
    ///  * {
    ///   padding: 0;
    ///   margin: 0;
    ///   box-sizing: border-box;
    ///   outline: none;
    ///   text-decoration: none;
    ///   list-style: none;
    ///  }
    ///
    ///  .preheader {
    ///   display: none !important;
    ///   visibility: hidden;
    ///   opacity: 0;
    ///   color: transparent [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string Email_Feedback_Body {
        get {
            return ResourceManager.GetString("Email_Feedback_Body", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &lt;tr&gt;
    ///												&lt;td class=&quot;force-col&quot; valign=&quot;top&quot;
    ///													style=&quot;border:2px solid #FFFFFF;padding: 15px 30px 15px 30px; background: #f7f7f7;&quot;&gt;
    ///												{_AssessedOn_}
    ///												&lt;/td&gt;
    ///                                                &lt;td class=&quot;force-col&quot; valign=&quot;top&quot; style=&quot;border:2px solid #FFFFFF;padding: 15px 30px 15px 30px; background: #f7f7f7;&quot;&gt;
    ///                                                {_Score_}
    ///                                                &lt;/td&gt;
    ///                              [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string EmailAddAssessmentRow {
        get {
            return ResourceManager.GetString("EmailAddAssessmentRow", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 
    ///&lt;html lang=&quot;en-US&quot;&gt;
    ///&lt;head&gt;
    /// &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
    /// &lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1.0&quot; /&gt;
    /// &lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
    /// &lt;title&gt;Mailer&lt;/title&gt;
    /// &lt;style type=&quot;text/css&quot;&gt;
    ///  * {
    ///   padding: 0;
    ///   margin: 0;
    ///   box-sizing: border-box;
    ///   outline: none;
    ///   text-decoration: none;
    ///   list-style: none;
    ///  }
    ///
    ///  .preheader {
    ///   display: none !important;
    ///   visibility: hidden;
    ///   opacity: 0;
    ///   color: transpare [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string TeamLeader_FeedBack_Body {
        get {
            return ResourceManager.GetString("TeamLeader_FeedBack_Body", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 
    ///&lt;html lang=&quot;en-US&quot;&gt;
    ///&lt;head&gt;
    /// &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
    /// &lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1.0&quot; /&gt;
    /// &lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
    /// &lt;title&gt;Mailer&lt;/title&gt;
    /// &lt;style type=&quot;text/css&quot;&gt;
    ///  * {
    ///   padding: 0;
    ///   margin: 0;
    ///   box-sizing: border-box;
    ///   outline: none;
    ///   text-decoration: none;
    ///   list-style: none;
    ///  }
    ///
    ///  .preheader {
    ///   display: none !important;
    ///   visibility: hidden;
    ///   opacity: 0;
    ///   color: transpare [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string TeamLeaderFeedBack_Body {
        get {
            return ResourceManager.GetString("TeamLeaderFeedBack_Body", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 
    ///
    ///&lt;html lang=&quot;en-US&quot;&gt;
    ///&lt;head&gt;
    /// &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
    /// &lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1.0&quot; /&gt;
    /// &lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
    /// &lt;title&gt;Mailer&lt;/title&gt;
    /// &lt;style type=&quot;text/css&quot;&gt;
    ///  * {
    ///   padding: 0;
    ///   margin: 0;
    ///   box-sizing: border-box;
    ///   outline: none;
    ///   text-decoration: none;
    ///   list-style: none;
    ///  }
    ///
    ///  .preheader {
    ///   display: none !important;
    ///   visibility: hidden;
    ///   opacity: 0;
    ///   color: transpa [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string TeamLeaderFeedbackEmail {
        get {
            return ResourceManager.GetString("TeamLeaderFeedbackEmail", resourceCulture);
        }
    }
}
